// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_YnMi6IgX1Kj1u3egUJYL65zmkfFBh4Y',
    appId: '1:96719860947:web:6072dd74a98c940267d026',
    messagingSenderId: '96719860947',
    projectId: 'gmatapp-a7b1a',
    authDomain: 'gmatapp-a7b1a.firebaseapp.com',
    storageBucket: 'gmatapp-a7b1a.appspot.com',
    measurementId: 'G-Z9JFGX5LQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVvW10mBpZ-cS5CF2C6FMxT7jHbR2Tw0',
    appId: '1:96719860947:android:369042fd6262e2be67d026',
    messagingSenderId: '96719860947',
    projectId: 'gmatapp-a7b1a',
    storageBucket: 'gmatapp-a7b1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYa612jAAYVYCxzW0g2TUBTNsMfa-3lxQ',
    appId: '1:96719860947:ios:da7d60c051b5420f67d026',
    messagingSenderId: '96719860947',
    projectId: 'gmatapp-a7b1a',
    storageBucket: 'gmatapp-a7b1a.appspot.com',
    iosClientId: '96719860947-6c85pgscl4ainjg1pu1qnbdqv5v4f7b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYa612jAAYVYCxzW0g2TUBTNsMfa-3lxQ',
    appId: '1:96719860947:ios:da7d60c051b5420f67d026',
    messagingSenderId: '96719860947',
    projectId: 'gmatapp-a7b1a',
    storageBucket: 'gmatapp-a7b1a.appspot.com',
    iosClientId: '96719860947-6c85pgscl4ainjg1pu1qnbdqv5v4f7b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
